### ISSUE TITLE
Arrow notation causes this to fail?

### ISSUE THREAD

**Issue by tdhz77** [ZJONSSON/pacer#1]
ran npm install
node index.js
SyntaxError: Unexpected token =>

Am I missing something?

**Comment by ZJONSSON** [comment]
This repo was written with ES6 and should run on node 4+  (I'm using 5.5.0 stable)
I'm guessing you could also run this with `babel-node` (see [here](https://babeljs.io/docs/usage/cli/))

Let me know if this does not work

**Comment by tdhz77** [comment]
I'm running node v.5.0
